version: "3.8"
services:
  bf1942:
    image: sjkp/bf1942
    command: sh -c "/start.sh"
    ports:
      - 14567:14567/udp # Server
      - 15667:15667/tcp # BFSM
      - 22000:22000/udp # Gamespy LAN
      - 23000:23000/udp # Gamespy
    working_dir: /
    volumes:
      - bf1942-mods:/bf1942/mods/ # Persistent mods directory
    environment:
      BFSM: "yes"
      SERVER_NAME: "NEWSERVER"
      SERVER_PASSWORD: "test"
      SERVER_MESSAGE: ""
      ADMIN_PASSWORD: "test"    
volumes:
  bf1942-mods:
